name: "test-deploy"

on:
  push:
    branches:
      - test

jobs:
  test:
    name: "Test Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Deploy AWS
        uses: "Geun-Oh/Composite-S3-CloudFront@0.2.2"
        with:
          filepath: "/test"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
